name: Check uvx-ready

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv self update
    - name: Install system dependencies (samtools)
      run: |
        sudo apt update
        sudo apt install -y samtools
    - name: Test run tool with uvx
      run: |
        uvx --from git+https://github.com/MViscardi-UCSC/ANDROMEDA andromeda run-all --help
